Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np
import seaborn as sns

X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110]) #zp
Y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]) #ks



In [2]:

x = X.reshape((10,1))
X


array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
  
y = Y.reshape((10,1))
Y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
#c использованием интерсепт
x = np.hstack([np.ones((10,1)),x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [5]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
B

array([[444.17735732],
       [  2.62053888]])

In [6]:
#без использования интерсепт
x = X.reshape((10,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [7]:
B = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
B

array([[5.88982042]])

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [35]:
def mse_(B1,y = Y,x = X, n = 10 ):
    return np.sum((B1*X-y)**2)/n

alfa, B1,n = 1e-6, 0.1,10

print(f"{alfa} {B1} {n}")


for i in range(1000):
    B1-=alfa*(2/n)*np.sum((B1*X-Y)*X)
   
    if i%100==0:
        print(f"Iteration {i}, B1 = {B1}, mse {mse_(B1)}")
        


1e-06 0.1 10
Iteration 0, B1 = 0.25952808, mse 493237.7212546963
Iteration 100, B1 = 5.54537842245223, mse 58151.31823171113
Iteration 200, B1 = 5.868748638669329, mse 56522.97550129376
Iteration 300, B1 = 5.888531320728348, mse 56516.88130936019
Iteration 400, B1 = 5.8897415574471985, mse 56516.85850140053
Iteration 500, B1 = 5.889815595583751, mse 56516.858416040064
Iteration 600, B1 = 5.889820124983314, mse 56516.85841572062
Iteration 700, B1 = 5.889820402076462, mse 56516.85841571941
Iteration 800, B1 = 5.88982041902807, mse 56516.8584157194
Iteration 900, B1 = 5.889820420065112, mse 56516.85841571941
Iteration 0, B1 = 1.1347302, mse 368017.9491755833
Iteration 100, B1 = 5.598920289974488, mse 57682.67406321302
Iteration 200, B1 = 5.872024146706, mse 56521.22156616817
Iteration 300, B1 = 5.8887317050891275, mse 56516.874745129535
Iteration 400, B1 = 5.8897538162759355, mse 56516.858476833426
Iteration 500, B1 = 5.8898163455368975, mse 56516.85841594815
Iteration 600, B1 = 5.8898201

104.32540042334865 5.325400423349019
